# Generated by Django 4.2.7 on 2023-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('state', models.CharField(default='InProgress', max_length=20)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('guessed_word', models.CharField(default='', max_length=50)),
                ('guesses', models.TextField(default='[]')),
                ('max_incorrect_guesses', models.IntegerField(default=0)),
            ],
        ),
    ]
